seed: 42
num_workers : 4

model_name : 'sgaligner'
modules    : ['gcn', 'point', 'rel', 'attr']

data :
  name           : Scannet
  root_dir       : /local/home/sdebsarkar/Documents/datasets/Scannet
  ply_subfix     : _vh_clean_2.labels.ply
  seg_subfix     : _vh_clean_2.0.010000.segs.json
  aggre_subfix   : _vh_clean.aggregation.json
  pred_subfix    : inseg.ply